storage: /verdaccio/storage
plugins: /verdaccio/plugins

web:
  enable: true
  title: Verdaccio (local)

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

filters:
  cooldown-filter:
    minAgeDays: {{MIN_AGE_DAYS}}

log:
  type: stdout
  format: pretty
  level: http